name: Build LaTeX Resume

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ closed ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache default LaTeX directory
        uses: actions/cache@v4
        with:
          path: /tmp/latex-action
          key: ${{ runner.os }}-latex-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-latex-

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          compiler: pdflatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Vijaya_Gopinadh_Resume
          path: resume.pdf