name: Build and Deploy

on:
  push:
    branches:
      - development
  pull_request:
    types:
      - closed
    branches:
      - testing

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache dependencies and build output
        uses: actions/cache@v4
        with:
          # Caches: Node modules, Next.js build cache, LaTeX directory
          path: |
            ~/.npm
            ${{ github.workspace }}/portfolio/.next/cache
            /tmp/latex-action
          # Hash based on OS, package-lock.json and source files for Next.js and LaTeX
          key: ${{ runner.os }}-build-cache-${{ hashFiles('portfolio/**/package-lock.json') }}-${{ hashFiles('portfolio/**/*.[jt]s', 'portfolio/**/*.[jt]sx', '**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-${{ hashFiles('portfolio/**/package-lock.json') }}-
            ${{ runner.os }}-build-cache-

      - name: Install dependencies
        working-directory: ./portfolio
        run: npm install

      - name: Build Portfolio
        working-directory: ./portfolio
        run: npm run build

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./resume/senior_data_engineer.tex
          compiler: pdflatex

      - name: Upload Resume PDF artifact
        uses: actions/upload-artifact@v4
        with:
          path: senior_data_engineer.pdf

      - name: Prepare Static Artifacts
        run: |
          mkdir -p portfolio/out
          cp senior_data_engineer.pdf portfolio/out/resume.pdf
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/out
          publish_branch: gh-pages
          force_orphan: true
